In [23]:
import torch
import numpy as np

x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
x = torch.rand(5,3)
print(x)

tensor([[0.9858, 0.1410, 0.5942],
        [0.2883, 0.2886, 0.6635],
        [0.1665, 0.7578, 0.1121],
        [0.4221, 0.6559, 0.8494],
        [0.6812, 0.7126, 0.5308]])


In [10]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)
y = np.zeros((5,3)).astype('float32')
print(y)
print(y.shape)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5, 3)


In [6]:
x = torch.tensor([5,3])
print(x)

tensor([5, 3])


In [12]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2109, -1.6028,  0.8447],
        [-0.5986,  0.1607, -0.2208],
        [-1.1453, -0.1742, -0.6411],
        [ 0.3007, -1.1321,  1.2223],
        [-0.7188, -0.5976, -1.3838]])
torch.Size([5, 3])


In [13]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 1.0014, -1.2464,  1.3996],
        [-0.1526,  0.9396,  0.2068],
        [-0.7811,  0.4219,  0.1322],
        [ 0.7952, -0.1693,  2.0379],
        [-0.1204, -0.2562, -0.7357]])


In [15]:
print(torch.add(x,y))

tensor([[ 1.0014, -1.2464,  1.3996],
        [-0.1526,  0.9396,  0.2068],
        [-0.7811,  0.4219,  0.1322],
        [ 0.7952, -0.1693,  2.0379],
        [-0.1204, -0.2562, -0.7357]])


In [16]:
result =  torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[ 1.0014, -1.2464,  1.3996],
        [-0.1526,  0.9396,  0.2068],
        [-0.7811,  0.4219,  0.1322],
        [ 0.7952, -0.1693,  2.0379],
        [-0.1204, -0.2562, -0.7357]])


In [18]:
y.add_(x)
print(y)

tensor([[ 1.0014, -1.2464,  1.3996],
        [-0.1526,  0.9396,  0.2068],
        [-0.7811,  0.4219,  0.1322],
        [ 0.7952, -0.1693,  2.0379],
        [-0.1204, -0.2562, -0.7357]])


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
x = torch.ones(2,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [28]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
print(y.grad_fn)

In [30]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        #Max pooling over a (2,2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features
    
net = Net()
print(net)
        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [33]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0121, -0.0583, -0.0329, -0.1879,  0.0294,  0.0538, -0.0126, -0.0327,
         -0.0280, -0.0775]], grad_fn=<AddmmBackward>)


In [34]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.7712, grad_fn=<MseLossBackward>)
