In [2]:
import numpy as np

In [7]:
# Broadcasting describes how arithmetic works betweem arrays of different shapes.

# Example of broadcasting with a scalar value and an array
arr = np.arange(5)
scalar = 5
x = arr * 5
# The scalar value has been broadcasted over the elements in the array to provide the value ([0,5,10,15,20])
print(x)

[ 0  5 10 15 20]


In [21]:
# Broadcasting can be utilised when demeaning each coloumn of an array by subracting the coloumn means

arr = np.random.randn(4,3)
demeaned = arr - arr.mean(0)
demeaned

(4, 3)
[[ 0.08795823 -0.06741107  0.32783973]]


array([[ 0.42035978,  1.12249542,  0.23223637],
       [ 0.14400249, -0.98473872,  0.63459033],
       [ 0.2260883 ,  0.48691656,  0.44628549],
       [-0.79045057, -0.62467326, -1.31311219]])

In [28]:
# Broadcasting rules
# Two arrays are compatiable for boradcasting if for each trailing dimension, the axis length match or if either of the length is 1.
# Bradcsting is then performed over the missing or length 1 dimensions
x = np.random.randn(4,3)
y = np.arange(3)
print(x.shape)
print(y.shape)
z = x + y
print(z)
print(z.shape)

(4, 3)
(3,)
[[ 0.22457548  1.08132967  3.13999419]
 [ 0.64542427  2.76195144  2.81692213]
 [-2.1710771   0.81952197  2.84549362]
 [-1.65151429  2.06608989  0.44980066]]
(4, 3)


In [36]:
# Subtracting the mean value from each row
arr = np.random.randn(4,3)
rows_mean = arr.mean(1)
print(arr.shape)
print(rows_mean.shape)
# For us to be able to subtract the mean from each row, the rows_mean wil require a shape of (4,1)
# As the rules states that two arrays are compatitable for broadcasting if for th trailing dimensions the axis length match or it's 1
rows_mean = rows_mean.reshape(4,1)
print(rows_mean.shape)
demeaned_rows = arr - rows_mean
print(demeaned_rows)
print(demeaned_rows.mean(1))

(4, 3)
(4,)
(4, 1)
[[ 1.17965534 -0.89907981 -0.28057553]
 [ 0.65780294 -0.86373361  0.20593066]
 [ 0.62719985 -0.08375451 -0.54344534]
 [-0.39411193  0.2286326   0.16547933]]
[ 0.00000000e+00  0.00000000e+00 -3.70074342e-17  1.85037171e-17]


In [45]:
x = np.random.randn(3,4,2)
y = np.random.randn(4,2)
z = x * y
print(z.shape)
print(z)

(3, 4, 2)
[[[ 1.07052385  0.48366055]
  [-0.04504526  0.78358673]
  [-0.24267379 -0.5947436 ]
  [-0.07156657 -0.78579781]]

 [[-1.0170226   0.21101584]
  [-0.27182785 -0.00591017]
  [-0.03903657 -0.9343431 ]
  [-0.36300249  0.51200076]]

 [[ 0.46380449 -0.19434254]
  [ 0.87233312 -2.70557699]
  [ 0.05607567  1.61036925]
  [-0.12692144  1.17330053]]]


In [ ]:
# When performing arithmetic operations with a lower dimensional array across axes other than zero
# According to the rule, the broadcast dimensions must be 1 in the smaller array

In [49]:
#1 Example without Broadcasting
a = np.array([1,2,3], dtype=float)
b = 5
c = np.empty([3])

for idx, i in enumerate(a):
    c[idx] = i * b

print(c)    

[ 5. 10. 15.]


In [50]:
#1 Example with Broadcasting
a = np.array([1,2,3], dtype=float)
b = 5
c = a * b
print(c)

[ 5. 10. 15.]


In [14]:
x = np.array([[2,3,4,5], [6,7,8,9]])
y = np.array([1,2,3,4])
z = x*y
print(z)

[[ 2  6 12 20]
 [ 6 14 24 36]]


In [15]:
print(x.shape)
print(y.shape)

(2, 4)
(4,)


In [17]:
x = np.array([[2,3,4,5], [6,7,8,9]])
y = np.array([[1,2,3,4], [1,2,3,4]])
z = x*y
print(z)

[[ 2  6 12 20]
 [ 6 14 24 36]]


In [18]:
print(x.shape)
print(y.shape)

(2, 4)
(2, 4)


In [23]:
print(np.empty([1,3]))
print(np.zeros([1,3]))

[[1.64719768e-066 6.80231464e-310 0.00000000e+000]]
[[0. 0. 0.]]


In [10]:
# Rule 1: The shaoe of the array must be the same

x = np.array([3,2,1])
y = np.array([6,5,2])
z = x * y
print(x.shape)
print(y.shape)
print(x.shape == y.shape)
print(z)

(3,)
(3,)
True
[18 10  2]


In [15]:
# Rule 2: 
# The number of dimensions in the arrays are the same, also
# the length of the dimensions is one that is shared across the arrays
# or the dimension of one of the array has a length of 1

x = np.array([[1,2,3,4], [5,6,7,8]])
y = np.array([2,3,5,3])
z = x * y
print(x.shape)
print(y.shape)
print(x.shape == y.shape)



(2, 4)
(4,)
False
